// This file was auto-generated by ML.NET Model Builder. 

using System;
using ConsoleApp9ML.Model;

namespace ConsoleApp9ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                HomeTeam = @"Fulham",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual FTHomeGol with predicted FTHomeGol from sample data...\n\n");
            Console.WriteLine($"HomeTeam: {sampleData.HomeTeam}");
            Console.WriteLine($"\n\nPredicted FTHomeGol: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
